// <auto-generated />
using CartNova.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartNova.Services.Migrations
{
    [DbContext(typeof(CouponDBContext))]
    [Migration("20260430152702_Data-seeded")]
    partial class Dataseeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartNova.Services.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.Property<string>("couponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            DiscountAmount = 10.0,
                            MinAmount = 50,
                            couponCode = "SAVE10"
                        },
                        new
                        {
                            CouponId = 2,
                            DiscountAmount = 8.0,
                            MinAmount = 40,
                            couponCode = "SAVE10"
                        },
                        new
                        {
                            CouponId = 3,
                            DiscountAmount = 9.0,
                            MinAmount = 50,
                            couponCode = "SAVE9"
                        },
                        new
                        {
                            CouponId = 4,
                            DiscountAmount = 6.0,
                            MinAmount = 30,
                            couponCode = "SAVE5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
